#!/bin/bash
# Read-only filesystem checker to be used with Red Hat Cluster.
#
# When the cluster performs a status check with this script, it
# will attempt to touch a file on each filesystem. If this fails,
# it will send a notification, then return an error status code.
# At this point it's up to the cluster suite to fence the affected
# node, so this needs to be configured in Luci / cluster.conf.
#
# Dependencies - nc must be installed.
#
# Settings below can be overrided from /etc/sysconfig/rofscheck by
# setting the following variables in that file:
#   $COMPANY - The company who this server belongs to.
#   $SID - The server ID
#   $NOTIFICATIONADDR - The email address to send the notification to
#   $SMTPRELAY - The server to use as an SMTP relay, IP only.
#
# The default SMTP relay should be left unless you have good reason to
# change it.

if [ -f /etc/sysconfig/rofscheck ]; then
    . /etc/sysconfig/rofscheck
fi

company=${COMPANY-"Change This Ltd"}
sid=${SID-"00000"}
notificationaddr=${NOTIFICATIONADDR-"alerts-cluster@ukfast.co.uk"}
smtprelay=${SMTPRELAY-"81.201.128.118"}

filesystems=$(cat /proc/mounts | grep '^/dev' | awk '{print $2}')
hostname=$(hostname -f)

function readonlyhandler {
# MTA might not be working with a read-only filesystem.
# Write email by hand and pipe to SMTP relay using nc.
# Sed is used to fix line endings since the default SMTP relay is strict.
    email=$(sed $'s/$/\r/' <<EOF
HELO ${hostname}
MAIL FROM:<rofscheck@${hostname}>
RCPT TO:<${notificationaddr}>
DATA
From: Read-only Filesystem Checker <rofscheck@${hostname}>
To: <${notificationaddr}>
Subject: Red Hat Cluster Error - Read-only Filesystem Detected [SID:${sid}]

A read-only filesystem has been detected on SID ${sid} belonging to ${company}.

This server should now be fenced. Please check this immediately.
.
QUIT
EOF
)
    echo -e "${email}" | /usr/bin/nc ${smtprelay} 25 > /dev/null 2>&1
    exit 254
}

case "$1" in
  start)
      exit 0
  ;;

  stop)
      exit 0 
  ;;

  status)
      for fs in $filesystems; do
          touch ${fs}/fscheck > /dev/null 2>&1 || readonlyhandler
          rm -f ${fs}/fscheck
      done
      exit 0
  ;;

  *)
      echo "Usage: $0 {start|stop|status}"
      exit 2
esac

